### ISSUE TITLE
Customer registration with username doesn't function

### ISSUE THREAD

**Issue by asoumya7** [diglin/Diglin_Username#22]
Good morning Diglin 

I have a big issue, i can't create a new customer after installing your extension. I added username to each customer who doesn't already have one and i tired to login so it works well, but i can't create a new customer i couldn't understand why. I use Magento 1.9.2.2, is it not compatible with it??

Thank you so much

**Comment by diglin** [comment]
Hi, as I have no capacity at this time to take a look, you may have an issue with a module overwriting the same customer model. As it's an open source project, you are free to analyze or ask a dev to do it for you. You are unfortunately on your own. 

Normally works on this magento version as I received good feedback. 
Regards

**Comment by asoumya7** [comment]
Thank you so much for your answer. Surly, there are a module that overwrite this "login" model because when i tried registration from billing information (when i tested a purchase with registration" it works very well and my customer was registered.

i will try to find issue, if i have any news i will publish it. 
Regards.

**Comment by asoumya7** [comment]
Good Afternoon,

I am so sorry for disturbing, i have just a very small question, i want to
retrieve username customer after registration, how does i get it?

In fact, i changed username as phone number so i need to retrieve this
phone number in order to send sms,  i found just mutter to how get it?

thank you so much for help :)

2016-01-06 12:52 GMT+01:00 Sylvain Rayé <notifications@github.com>:

> Hi, as I have no capacity at this time to take a look, you may have an
> issue with a module overwriting the same customer model. As it's an open
> source project, you are free to analyze or ask a dev to do it for you. You
> are unfortunately on your own.
>
> Normally works on this magento version as I received good feedback.
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diglin/Diglin_Username/issues/22#issuecomment-169307249>
> .
>



-- 
Cordialement

**Comment by diglin** [comment]
You can view the customer account from Magento Backend (Customer Managemenr) and get the username from the general information tab (where there is the name and lastname and so on)

Regards
Sylvain

**Comment by asoumya7** [comment]
Good morning 

I am so sorry for disturbing, i found the solution ^_^ and my SMS sending is work ^^
i just retrieve username by $_POST['username']

Thank you so much
