### ISSUE TITLE
i cann't fount Username notification  as ""Username" has not only digit characters."

### ISSUE THREAD

**Issue by asoumya7** [diglin/Diglin_Username#23]
Good afternoon Diglin

Please could you help me for this, i searcht all username module files but i can't found this notification in order to do my cutomisation 

Please just tell me where or how can i find this files???!!

Thank you so much

**Comment by diglin** [comment]
Hi

It's not in the extension as it uses the core feature of Magento related to attribute validation. You have to find the method validate in Mage_Eav Module, I think

Regards
Sylvain

**Comment by asoumya7** [comment]
Good morning ;

Thank you so much, i found the file
in code\core\Mage\Eav\Model\Attribute\Data\Abstract.php

Have a nice day.

Thank you again.

2016-01-19 22:38 GMT+01:00 Sylvain Rayé <notifications@github.com>:

> Hi
>
> It's not in the extension as it uses the core feature of Magento related
> to attribute validation. You have to find the method validate in Mage_Eav
> Module, I think
>
> Regards
> Sylvain
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diglin/Diglin_Username/issues/23#issuecomment-172995322>
> .
>



-- 
Cordialement
