### ISSUE TITLE
Module can't be deactivated

### ISSUE THREAD

**Issue by computer-spezialisten-de** [diglin/Diglin_Username#29]
Hello

if we deactivate the module for an single store the username don't dissapear at register and loginpage.
Even if we switch "off" the "Enable Username Support" global (in the module config) the inputs for username do not dissapear.

Greethings from Germany

Manuel Luckey

**Comment by diglin** [comment]
You have to adapt your template files per store view for that
Cheers

**Comment by computer-spezialisten-de** [comment]
All Stores use the same template! Is there no way to use the html switch?
For now we copy your template in our custom template and insert a swicht:

$noUsername = (in_array(Mage::app()->getStore()->getWebsiteId(),array(7,10)))
? true : false;

Mit freundlichen Grüßen

*Manuel Luckey*
*- Geschäftsführer*
*MCL Computer-Spezialisten.de GmbH*
*Telefon:* +49 7556 928899-0
*Email:* m.luckey@computer-spezialisten.de
*Web:* www.computer-spezialisten.de
[image: Google+]  <https://plus.google.com/109243529578809916462/>[image:
Facebook] <https://www.facebook.com/manuel.luckey>Römerstr. 2
88690 Uhldingen-Mühlhofen
Tel.: 07556 928899-0
Fax: 07556 928899-9
Geschäftsführer: Manuel Luckey
Registergericht: Freiburg i. Br.
HRB: 705501

2016-08-15 11:39 GMT+02:00 Sylvain Rayé <notifications@github.com>:
