### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by vinitchopra12** [diglin/Diglin_Username#30]
When I am trying to create an account its redirect to the same (registration) page without any message and values. In backend the customer is also not created. I am using this extension in Magento 1.9.2.4.

**Comment by diglin** [comment]
What say your log files ?

**Comment by vinitchopra12** [comment]
I have updated the extension with the repo. Now I am getting the new error msg as "Cannot save the customer." but the customer is created. See this screenshot: http://puu.sh/r55aA/78b25b2acb.png

**Comment by diglin** [comment]
Sorry for the delay. What says your log files about the error ?

**Comment by whizkid79** [comment]
same issue here. The logs are empty. if i create a customer in the backend, i can login and log out. but creating a new customer in the frontend doesn't work.
I'm using the composer version.

**Comment by whizkid79** [comment]
looks like the formkey is missing. adding this line to the template `vendor/diglin/diglin_username/src/app/design/frontend/base/default/template/username/persistent/customer/form/register.phtml` seems to fix it:
`            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
`
No sure if it break backwards-compatibility.

**Comment by diglin** [comment]
You use a old version of the extension. The current release has already this solution implemented: https://github.com/diglin/Diglin_Username/blob/master/src/app/design/frontend/base/default/template/username/persistent/customer/form/register.phtml#L36
