### ISSUE TITLE
Rename default column name "Username" in Manage Customers Grid

### ISSUE THREAD

**Issue by kendy2562** [diglin/Diglin_Username#36]
Hi, 

I have select Yes for option - Display username in "Manage Customers" Grid.
May I know how can we rename the default column name "Username" "Manage Customers" Grid to name we wanted.

Thank you.

**Comment by diglin** [comment]
Hi, you can trick it by creating a translate.csv into your admin theme and set "Diglin_Username:Username","What ever you want". It's just a suggestion which is not tested
